version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: weekly
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    labels:
      - dependencies
      - automation
